name: jira
type: java:8
disk: 2048

relationships:
    jiradb: "jiradb:postgresql"
  
mounts:
    home:
        source: local
        source_path: 'home'
  
web:
    commands:
        start: "sh ./start.sh"

hooks:
    build: "bash ${PLATFORM_APP_DIR}/build.sh"
    deploy: "sh ${PLATFORM_APP_DIR}/deploy.sh"

